<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bank Transfer</name>
   <tag></tag>
   <elementGuidId>13f75002-9854-4e23-a29c-fd33980dc87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div/div/div/div[6]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-hr69ez.r-1loqt21.r-16l9doz.r-1guathk.r-rjfia.r-1otgn73.r-1i6wzkk.r-lrvibr.r-13qz1uu > div.css-1dbjc4n.r-1awozwy.r-13awgt0.r-18u37iz.r-1wtj0ep.r-mk0yit > div.css-1dbjc4n.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md > div.css-901oao.r-jwli3a.r-t1w4ow.r-1b43r93.r-majxgm.r-rjixqe.r-1yzf0co.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47d7c72c-dba3-41a7-bb87-bfc5cbf4585b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>af036def-e947-42a9-88ac-d565d902150c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-majxgm r-rjixqe r-1yzf0co r-fdjqy7</value>
      <webElementGuid>aaedeee1-be4e-4034-9076-e3920399aab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bank Transfer</value>
      <webElementGuid>3f94abf4-3e74-4f2b-b353-8332bcfe9229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-mabd2g&quot;]/div[@class=&quot;css-1dbjc4n r-ywje51 r-zd98yo r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-13awgt0 r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-1492nhi r-kdyh1x r-1yos0t3 r-13awgt0 r-18u37iz r-1h0z5md r-1udh08x r-1wi2xyk&quot;]/div[@class=&quot;css-1dbjc4n r-1pi2tsx&quot;]/div[@class=&quot;css-1dbjc4n r-1492nhi r-6t5ypu r-kicko2 r-5vf7qs r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-hr69ez r-1loqt21 r-16l9doz r-1guathk r-rjfia r-1otgn73 r-1i6wzkk r-lrvibr r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1wtj0ep r-mk0yit&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1h0z5md&quot;]/div[@class=&quot;css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-majxgm r-rjixqe r-1yzf0co r-fdjqy7&quot;]</value>
      <webElementGuid>ec356528-000d-47c2-8f2f-b7cb7ecbf8f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div/div/div/div[6]/div/div/div</value>
      <webElementGuid>cc847ab1-d646-4be7-8ac3-b0d5e8fa8c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div</value>
      <webElementGuid>79a5a0ad-77cc-43b3-8c07-322df6be34b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bank Transfer' or . = 'Bank Transfer')]</value>
      <webElementGuid>210cc59e-41f1-4655-b934-19e9f9e65104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
