<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_css-11aywtz r-z2wwpe r-t1w4ow r-1b43r_2162d1</name>
   <tag></tag>
   <elementGuidId>08ba4891-5f5e-4c91-8624-afa37151ddec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-14lw9ot.r-kdyh1x.r-b4qz5r.r-1ifxtd0.r-nsbfu8.r-184en5c > div.css-1dbjc4n.r-eqz5dr > div.css-1dbjc4n.r-14lw9ot.r-kdyh1x.r-da5iq2 > div.css-1dbjc4n > div.css-1dbjc4n.r-391gc0.r-nsbfu8 > div.css-1dbjc4n.r-184en5c > div.css-1dbjc4n.r-14lw9ot.r-1e4vmmq > div.css-1dbjc4n > div.css-1dbjc4n.r-u4s1nx.r-z2wwpe.r-rs99b7.r-bnwqim > input.css-11aywtz.r-z2wwpe.r-t1w4ow.r-1b43r93.r-majxgm.r-mabqd8.r-rjixqe.r-cwlir5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92feb4e8-89d1-4cb5-abde-44eec0b67f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search location or address</value>
      <webElementGuid>83f7fa1a-455f-41b6-87a0-f6a9b59f6573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>a9487101-5177-477a-ac7e-9fb61089598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>be0caa62-e7bd-4525-b674-d2447e0e469f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a2042d3d-a476-40bb-a818-9a0110d266cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8919ee40-3bed-458c-bad8-5d5e94a7e2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c8d7eba-2fcf-4261-ab9e-946cfe726779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4e9a8e5-7d5e-4ea5-aa1c-cf2f7e2a2ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-z2wwpe r-t1w4ow r-1b43r93 r-majxgm r-mabqd8 r-rjixqe r-cwlir5</value>
      <webElementGuid>7e0f9649-0d37-4f15-8a86-05d20effcee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RENTAL_DROPOFF_LOCATION&quot;)/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-b4qz5r r-1ifxtd0 r-nsbfu8 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-nsbfu8&quot;]/div[@class=&quot;css-1dbjc4n r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1e4vmmq&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-u4s1nx r-z2wwpe r-rs99b7 r-bnwqim&quot;]/input[@class=&quot;css-11aywtz r-z2wwpe r-t1w4ow r-1b43r93 r-majxgm r-mabqd8 r-rjixqe r-cwlir5&quot;]</value>
      <webElementGuid>d7dd0863-07ac-4a14-9242-392eaef15039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>96c7ba7a-cbf2-42d8-8043-465271a76f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RENTAL_DROPOFF_LOCATION']/div/div/div[5]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>46eee7f6-08d3-4e7c-9428-f9fd85f443ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>ebcaffb0-c248-464e-8430-83050ed0bfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search location or address' and @type = 'text']</value>
      <webElementGuid>bef1f6ea-4f2c-4bcf-9532-29ad507da4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
