<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>awswaf-captcha-latform-012</name>
   <tag></tag>
   <elementGuidId>3e75276c-cce6-4e6f-84a1-3ebf6d39730d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>awswaf-captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>awswaf-captcha</value>
      <webElementGuid>9ccd10c5-5b16-41f9-8870-c16a49e96c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>cf12a2d5-4e87-45a0-8814-a64b2da31e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aws-captcha&quot;)/awswaf-captcha[1]</value>
      <webElementGuid>06791bfc-aebd-4dd0-a25a-977ad79c92dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      <webElementGuid>c471732b-4364-449d-be70-f04ad4239cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//awswaf-captcha</value>
      <webElementGuid>3222550b-3618-41e4-9ca4-419addf5b18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
