<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm-orm-012-902</name>
   <tag></tag>
   <elementGuidId>1d0b0f8b-7a21-436d-9ccb-5cd683293c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div[6]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.amzn-captcha-modal > form > div:nth-of-type(6) > div:nth-of-type(2) > #amzn-btn-verify-internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8553e34d-7f4e-4bfa-82b1-327cdb629e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7694764-9037-4ea5-b290-12d9b38695e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amzn-btn-verify-internal</value>
      <webElementGuid>b36d287b-cfb8-450e-8ce5-45c528c46ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ab225b76-2d48-4ab7-b7a4-6e5217488beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>46119125-6e5a-48de-a908-5e455d31ac99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;root&quot;]/div[@class=&quot;amzn-captcha-modal&quot;]/form[1]/div[6]/div[2]/button[@id=&quot;amzn-btn-verify-internal&quot;]</value>
      <webElementGuid>90c29282-5f1f-4b0a-8d4e-5cd16de113fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Traveloka Car/Page_Traveloka - Southeast Asias Leading Tr_13aaf0/awswaf-captcha-latform-012</value>
      <webElementGuid>12b8b165-fabe-4d8e-bbf2-944538aec56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48e43233-1948-4a2e-b0e6-cf511b098f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[6]/div[2]/button</value>
      <webElementGuid>8ba61e9a-9610-420d-8e64-09da60e393ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'amzn-btn-verify-internal' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>34f9c3ca-df08-4a8e-b6fa-251b4c075ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
