<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas-orm-012-991</name>
   <tag></tag>
   <elementGuidId>51e3a43f-f9a3-4489-aa63-d92e6a5eef6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div[2]/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.amzn-captcha-modal > form > div:nth-of-type(2) > div > canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>f72dfcfc-1132-4ca6-a655-c54cb03b8ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>c1cce152-d56f-438c-8cfa-67ee77974915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>5d4e6767-3979-4748-9f85-d12856f17467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;root&quot;]/div[@class=&quot;amzn-captcha-modal&quot;]/form[1]/div[2]/div[1]/canvas[1]</value>
      <webElementGuid>f13a3627-d720-4e03-96bd-67de66804305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Traveloka Car/Page_Traveloka - Southeast Asias Leading Tr_13aaf0/awswaf-captcha-latform-012</value>
      <webElementGuid>258a6a99-da83-4a64-be1f-a86ec1a17bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99f2ef9e-c8c1-48c6-848e-f363835f83a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[2]/div/canvas</value>
      <webElementGuid>f5ecc093-4dd6-432a-aeb6-cae8ca8f1221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
