<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log In</name>
   <tag></tag>
   <elementGuidId>68d524a6-a25e-4c1b-990c-dff4cd36d965</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Log In' or . = 'Log In')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-jwli3a.r-t1w4ow.r-1b43r93.r-majxgm.r-rjixqe.r-4amgru.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b62076a1-3fc0-4852-a1c6-2729d31749e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a863d83b-72e4-4622-8caa-b4ab804f8ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-majxgm r-rjixqe r-4amgru r-fdjqy7</value>
      <webElementGuid>d9efba0b-6da0-4a76-a666-ada4b39b974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>f97c4488-1292-4957-a61e-d7810a8e13e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-bztko3 r-ipm5af r-iy1yoi r-13qz1uu r-8ny0jo&quot;]/div[@class=&quot;css-1dbjc4n r-wy61xf r-1jgb5lz r-r0h9e2 r-u8s1d r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1777fci r-10gryf7 r-82yag r-u8s1d r-iy1yoi r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep r-1e081e0 r-oyd9sg r-17yavnb r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-11mg6pl r-kdyh1x r-rs99b7 r-1loqt21 r-18u37iz r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-majxgm r-rjixqe r-4amgru r-fdjqy7&quot;]</value>
      <webElementGuid>a06364e8-fe45-43b8-a288-e93e2ba03a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>84a2f03b-4469-4b06-9079-dcae998eb41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>8230ff4e-78d4-4a45-8ed8-8b0b622ef98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>703423e6-aca3-48d5-8861-1b765d907f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
