<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Car Rental</name>
   <tag></tag>
   <elementGuidId>897da649-7271-4f71-bc47-b18ed7023c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/a[6]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.css-4rbku5.css-901oao.r-jwli3a.r-t1w4ow.r-1b43r93.r-b88u0q.r-1cwl3u0.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d5fa4e07-e774-45a7-ae6c-f1de563f80f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1afeade3-20d3-4b7b-8750-40cc734c4b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fe36b504-50fc-474c-832a-96e3c4d9aec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>ed545330-a801-40b1-9a27-03e87c266b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-b88u0q r-1cwl3u0 r-fdjqy7</value>
      <webElementGuid>b4dccc34-8128-4e6e-86b0-a0c31ee0018a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Car Rental</value>
      <webElementGuid>082a246c-ff71-478b-9632-49b3b53d2a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-bztko3 r-ipm5af r-iy1yoi r-13qz1uu r-8ny0jo&quot;]/div[@class=&quot;css-1dbjc4n r-wy61xf r-1jgb5lz r-r0h9e2 r-u8s1d r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1777fci r-10gryf7 r-82yag r-u8s1d r-iy1yoi r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-qklmqi r-1dppl8s r-5kkj8d r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6koalj r-1ugchlj r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-tzz3ar r-1pi2tsx r-1ktosi0 r-mrxtjd r-s1qlax r-13qz1uu&quot;]/a[@class=&quot;css-4rbku5 r-1awozwy r-2lfw2k r-kdyh1x r-6koalj r-88pszg r-1p6iasa r-1pn2ns4&quot;]/h4[@class=&quot;css-4rbku5 css-901oao r-jwli3a r-t1w4ow r-1b43r93 r-b88u0q r-1cwl3u0 r-fdjqy7&quot;]</value>
      <webElementGuid>ce3ea2e8-3ae2-414e-aa9d-a151a9d1304a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/a[6]/h4</value>
      <webElementGuid>9dcc048d-beac-480b-815c-e853b72503f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/h4</value>
      <webElementGuid>b8a07237-c193-4fbf-b5c2-f53ca57c9f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Car Rental' or . = 'Car Rental')]</value>
      <webElementGuid>9b599e0e-e88f-433a-b17a-ae8f38f23fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
