<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Inflate the ti</name>
   <tag></tag>
   <elementGuidId>f3f2c969-26c2-4acd-b3d1-726054bb1389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[2]/div/div[9]/div/div/div[3]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.css-11aywtz.r-13awgt0.r-t1w4ow.r-ubezar.r-majxgm.r-135wba7.r-bcqeeo.r-1ny4l3l.r-10paoce.r-13n6l4s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9f6dac65-5cd5-404b-b403-e4929705686e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Odd or even license plates, car charger, baby car seat, etc.</value>
      <webElementGuid>f372b11f-27c4-4435-8367-88a1d4a26807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d3c77d3-9a30-41d2-bb06-9d64efac3c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>d55e7ff6-7be0-462c-98ea-f44fd99d991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7b0d39fa-58fb-43a1-bcbf-7ced4d888f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3d1b8e2b-d124-4ae9-b5e5-170c78224dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>81040a11-4229-446d-ab93-88c5373276b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c65fe6e0-03b9-424e-81f4-b15ed1a129c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>904ef246-da98-4def-a689-b0f7d7c1bc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-13awgt0 r-t1w4ow r-ubezar r-majxgm r-135wba7 r-bcqeeo r-1ny4l3l r-10paoce r-13n6l4s</value>
      <webElementGuid>1430675b-949d-4e97-961b-764caca39c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d4afb69-5792-494e-9d4a-a38b43bbde3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inflate the ti</value>
      <webElementGuid>64d9f89f-d12b-4493-a4ef-c9d8fed00c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1kihuf0 r-16y2uox r-15g7tld r-11c0sde r-uwe93p r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep&quot;]/div[@class=&quot;css-1dbjc4n r-tzxfm6&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr r-nsbfu8&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1777fci r-edyy15&quot;]/textarea[@class=&quot;css-11aywtz r-13awgt0 r-t1w4ow r-ubezar r-majxgm r-135wba7 r-bcqeeo r-1ny4l3l r-10paoce r-13n6l4s&quot;]</value>
      <webElementGuid>e67f1b78-6e93-4e2f-a2c4-c52bf86ee69b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[2]/div/div[9]/div/div/div[3]/div/textarea</value>
      <webElementGuid>cf9affa0-910e-46f7-b8b1-2b7c1ef5ba60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0da63019-0a9d-409b-8d70-43172d7286a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Odd or even license plates, car charger, baby car seat, etc.' and (text() = 'Inflate the ti' or . = 'Inflate the ti')]</value>
      <webElementGuid>08ef7b84-c9e3-4f9f-972e-8b75a21df3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
